---
- name: Creating variable template
  vars:
     project_dir : "/var/lib/jenkins/workspace/erraform-Ansible-Pipeline_master"
  template:
    src: variables.tf.j2
    dest: "{{ project_dir }}/templates/variables.tf"

- name: Executing Terraform
  terraform:
    project_path: '{{ project_dir }}'
    lock: true
    force_init: yes
    state: "{{ state }}"
    plan_file: "vpc.plan"
  register: tf_output

- name: Print Outputs
  debug:
    var: tf_output
