---
- name: Creating variable template
  template:
    src: variables.tf.j2
    dest: "./variables.tf"

- name: Executing Terraform
  terraform:
    project_path: "/var/lib/jenkins/workspace/erraform-Ansible-Pipeline_master"
    lock: true
    force_init: yes
    state: "{{ state }}"
    plan_file: "vpc.plan"
  register: tf_output

- name: Print Outputs
  debug:
    var: tf_output
